language: php

php:
  - 7

env:
  - TYPO3_VERSION=^7.6.0
  - TYPO3_VERSION=^8.0.0
  - TYPO3_VERSION=dev-master

sudo: false
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/composer

addons:
  apt:
    packages:
      - parallel

before_install:
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  # Rename our working directory, required for Extension upload to TER.
  - cd .. && mv typo3-extension-mediaoembed mediaoembed && cd mediaoembed
  - composer require typo3/cms=$TYPO3_VERSION
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  - if [ -d $PWD/.Build/vendor/typo3/cms/components ]; then ln -s "$PWD/.Build/vendor/typo3/cms/components" .Build/Web/components; fi

script:
  - >
    echo;
    echo "Running phpcs";
    .Build/bin/phpcs --config-set installed_paths $PWD/.Build/vendor/de-swebhosting/php-codestyle/PhpCodeSniffer
    .Build/bin/phpcs --standard=PSRDefault Classes Configuration/TCA Tests/Unit ext_emconf.php ext_localconf.php
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit  Tests/Unit/;
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
